# Generated by Django 6.0.6 on 2026-06-17 06:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titleTest', models.CharField(max_length=255)),
                ('classe', models.CharField(choices=[('Petit', 'Petit'), ('Débutant', 'Débutant'), ('Moyen', 'Moyen'), ('JuniorA', 'JuniorA'), ('JuniorB', 'JuniorB')], max_length=20)),
                ('typeTest', models.CharField(choices=[('EVALUATION', 'EVALUATION'), ('SUNDAY_SCHOOL', 'SUNDAY_SCHOOL'), ('CONCOURS', 'CONCOURS')], max_length=50)),
                ('sujetTest', models.URLField(blank=True, max_length=500, null=True)),
                ('correctionTest', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='children.child')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='test.test')),
            ],
            options={
                'unique_together': {('child', 'test')},
            },
        ),
    ]
