# Generated by Django 6.0.6 on 2026-06-17 03:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('NORMAL', 'NORMAL'), ('DLT', 'DLT'), ('SUNDAY_SCHOOL', 'SUNDAY_SCHOOL')], max_length=50)),
                ('classe', models.CharField(choices=[('Petit', 'Petit'), ('Débutant', 'Débutant'), ('Moyen', 'Moyen'), ('JuniorA', 'JuniorA'), ('JuniorB', 'JuniorB')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_seances', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_seances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
