# Generated by Django 6.0.6 on 2026-06-17 04:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
        ('seance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantSeance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seance_participations', to='children.child')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='seance.seance')),
            ],
            options={
                'unique_together': {('child', 'seance')},
            },
        ),
    ]
