# Generated by Django 6.0.6 on 2026-06-17 02:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('classe', models.CharField(choices=[('Petit', 'Petit'), ('Débutant', 'Débutant'), ('Moyen', 'Moyen'), ('JuniorA', 'JuniorA'), ('JuniorB', 'JuniorB')], max_length=20)),
                ('nivScolaire', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('telParent', models.CharField(blank=True, max_length=20, null=True)),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], max_length=15)),
                ('sexeParent', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], max_length=15)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
