# Generated by Django 6.0.6 on 2026-06-17 02:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eventType', models.CharField(choices=[('Arbre de noël', 'Arbre de noël'), ('Soirée récréative des enfants', 'Soirée récréative des enfants')], max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_links', to='activities.activity')),
            ],
        ),
    ]
