# Generated by Django 6.0.6 on 2026-06-20 18:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monthKey', models.CharField(max_length=7, unique=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'ordering': ['-monthKey'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateLabel', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='schedules.schedule')),
            ],
            options={
                'verbose_name': 'Schedule Row',
                'verbose_name_plural': 'Schedule Rows',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seance_type', models.CharField(choices=[('NORMAL', 'NORMAL'), ('SUNDAY_SCHOOL', 'SUNDAY_SCHOOL'), ('DLT', 'DLT')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_assignments', to=settings.AUTH_USER_MODEL)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='schedules.schedulerow')),
            ],
            options={
                'verbose_name': 'Schedule Assignment',
                'verbose_name_plural': 'Schedule Assignments',
                'ordering': ['seance_type'],
                'unique_together': {('row', 'teacher', 'seance_type')},
            },
        ),
    ]
