# Generated by Django 6.0.6 on 2026-06-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default='bac473bb041f4c20b9ff462eb7ba3551', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
