# Generated by Django 6.0.6 on 2026-06-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountverificationcode',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
