# Generated by Django 6.0.6 on 2026-06-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountverificationcode_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='sexe',
            field=models.CharField(blank=True, choices=[('Masculin', 'MASCULIN'), ('Feminin', 'FEMININ')], max_length=12),
        ),
    ]
