# Generated by Django 6.0.6 on 2026-06-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofil_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofil',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
